export const SUBSCRIPTION_PLUGIN_OPTIONS = Symbol('SUBSCRIPTION_PLUGIN_OPTIONS');
export const RAZORPAY_SUBSCRIPTION_PROVIDER = Symbol('RAZORPAY_SUBSCRIPTION_PROVIDER');
export const RECURRING_BILLING_PROVIDER = Symbol('RECURRING_BILLING_PROVIDER');
export const loggerCtx = 'SubscriptionPlugin';
